### ISSUE TITLE
setOverScrollMode() doesn't work

### ISSUE THREAD

**Issue by meNESS** [cymcsg/UltimateRecyclerView#238] opened 2015-11-16 08:34 UTC
Hi,

```recyclerView.setOverScrollMode(View.OVER_SCROLL_NEVER);``` doesn't work! I want to disable the glow of my recyclerview while scrolling vertically.

**Comment by vivian8725118** [comment] 2015-12-04 04:05
I have encountered this problem too when using scrollview,and I don't know how to solve it now.I just change the color of the glow so that it doesn't seem so obvious.

**Comment by alirezaaa** [comment] 2015-12-04 17:32
@vivian8725118 Don't worry. The owner added bug label to this issue, means he know what the problem is. It will be fixed soon I hope :)

**Comment by vivian8725118** [comment] 2015-12-05 00:31
WOW,that's cool,thanks

发自我的 iPhone

**Comment by jjhesk** [comment] 2016-05-25 07:17
@vivian8725118 did you try `mRecyclerView.recyclerview` to api this call?

**Closed** 2016-05-25 07:51 UTC
Labels: bug
